name: dulman_flutter
description: "둘만 - 1:1 프라이빗 커플 채팅 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  supabase_flutter: ^2.16.0
  drift: ^2.34.2
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
