CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS user_account (
  login_id varchar(64) PRIMARY KEY CHECK (login_id ~ '^[A-Za-z0-9._-]{3,64}$'),
  auth_user_id uuid NOT NULL UNIQUE,
  password_hash varchar(255),
  current_device_id varchar(128),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_a_id varchar(64) NOT NULL,
  user_b_id varchar(64),
  status varchar(16) NOT NULL CHECK (status IN ('waiting', 'active', 'ended')),
  invite_code varchar(32) NOT NULL UNIQUE,
  last_reset_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  ended_by_user_id varchar(64)
);

CREATE TABLE IF NOT EXISTS message (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id bigint NOT NULL,
  sender_id varchar(64) NOT NULL,
  type varchar(16) NOT NULL CHECK (type IN ('text', 'media')),
  text_content text,
  permission_type varchar(32) CHECK (permission_type IN ('once', 'replay_once', 'keep')),
  view_count integer NOT NULL DEFAULT 0 CHECK (view_count >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL,
  url text NOT NULL,
  mime_type varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_reset_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id bigint NOT NULL,
  reset_by_user_id varchar(64) NOT NULL,
  reset_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_read_state (
  chat_id bigint NOT NULL,
  user_id varchar(64) NOT NULL,
  last_read_message_id bigint NOT NULL DEFAULT 0,
  read_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE IF NOT EXISTS security_rate_limit (
  operation text NOT NULL,
  subject_key text NOT NULL,
  window_start timestamptz NOT NULL,
  request_count integer NOT NULL CHECK (request_count >= 0),
  PRIMARY KEY (operation, subject_key, window_start)
);

CREATE INDEX IF NOT EXISTS idx_chat_user_a_status ON chat (user_a_id, status);
CREATE INDEX IF NOT EXISTS idx_chat_user_b_status ON chat (user_b_id, status);
CREATE INDEX IF NOT EXISTS idx_message_chat_id_id ON message (chat_id, id);
CREATE INDEX IF NOT EXISTS idx_media_message_id ON media (message_id, id);
CREATE INDEX IF NOT EXISTS idx_chat_read_state_chat_user ON chat_read_state (chat_id, user_id);

CREATE OR REPLACE FUNCTION public.current_login_id()
RETURNS varchar(64)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT login_id FROM user_account WHERE auth_user_id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.consume_rate_limit(
  p_operation text,
  p_subject_key text,
  p_limit integer,
  p_window_seconds integer
)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_window_start timestamptz;
  v_count integer;
BEGIN
  v_window_start := to_timestamp(
    floor(extract(epoch FROM now()) / p_window_seconds) * p_window_seconds
  );

  INSERT INTO security_rate_limit (operation, subject_key, window_start, request_count)
  VALUES (p_operation, p_subject_key, v_window_start, 1)
  ON CONFLICT (operation, subject_key, window_start)
  DO UPDATE SET request_count = security_rate_limit.request_count + 1
  RETURNING request_count INTO v_count;

  RETURN v_count <= p_limit;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_chat()
RETURNS SETOF chat
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_login_id varchar(64) := current_login_id();
BEGIN
  IF v_login_id IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;
  IF NOT consume_rate_limit('chat_create', v_login_id, 10, 3600) THEN
    RAISE EXCEPTION 'RATE_LIMITED';
  END IF;
  IF EXISTS (SELECT 1 FROM chat WHERE status = 'active' AND (user_a_id = v_login_id OR user_b_id = v_login_id)) THEN
    RAISE EXCEPTION 'CHAT_ACTIVE_EXISTS';
  END IF;

  RETURN QUERY
  INSERT INTO chat (user_a_id, status, invite_code)
  VALUES (v_login_id, 'waiting', upper(encode(gen_random_bytes(6), 'hex')))
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.join_chat(p_invite_code text)
RETURNS SETOF chat
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_login_id varchar(64) := current_login_id();
  v_chat chat;
BEGIN
  IF v_login_id IS NULL THEN
    RAISE EXCEPTION 'AUTH_REQUIRED';
  END IF;
  IF NOT consume_rate_limit('chat_join', v_login_id, 5, 300) THEN
    RAISE EXCEPTION 'CHAT_INVITE_RATE_LIMITED';
  END IF;
  IF EXISTS (SELECT 1 FROM chat WHERE status = 'active' AND (user_a_id = v_login_id OR user_b_id = v_login_id)) THEN
    RAISE EXCEPTION 'CHAT_ACTIVE_EXISTS';
  END IF;

  SELECT * INTO v_chat FROM chat WHERE invite_code = upper(trim(p_invite_code)) FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'CHAT_INVITE_NOT_FOUND'; END IF;
  IF v_chat.status = 'ended' THEN RAISE EXCEPTION 'CHAT_NOT_ACTIVE'; END IF;
  IF v_chat.user_b_id IS NOT NULL OR v_chat.status = 'active' OR v_chat.user_a_id = v_login_id THEN
    RAISE EXCEPTION 'CHAT_FULL';
  END IF;

  RETURN QUERY
  UPDATE chat
  SET user_b_id = v_login_id, status = 'active'
  WHERE id = v_chat.id
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.send_text_message(p_chat_id bigint, p_text_content text)
RETURNS SETOF message
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_login_id varchar(64) := current_login_id();
  v_chat chat;
BEGIN
  SELECT * INTO v_chat FROM chat WHERE id = p_chat_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'CHAT_NOT_FOUND'; END IF;
  IF v_login_id IS NULL OR (v_chat.user_a_id <> v_login_id AND v_chat.user_b_id <> v_login_id) THEN
    RAISE EXCEPTION 'CHAT_PARTICIPANT_REQUIRED';
  END IF;
  IF v_chat.status <> 'active' THEN RAISE EXCEPTION 'CHAT_NOT_ACTIVE'; END IF;
  IF p_text_content IS NULL OR length(trim(p_text_content)) = 0 OR length(p_text_content) > 4000 THEN
    RAISE EXCEPTION 'MESSAGE_INVALID';
  END IF;
  IF NOT consume_rate_limit('message_send', v_login_id || ':' || p_chat_id, 60, 300) THEN
    RAISE EXCEPTION 'RATE_LIMITED';
  END IF;

  RETURN QUERY
  INSERT INTO message (chat_id, sender_id, type, text_content)
  VALUES (p_chat_id, v_login_id, 'text', trim(p_text_content))
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_chat_read(p_chat_id bigint, p_message_id bigint)
RETURNS SETOF chat_read_state
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_login_id varchar(64) := current_login_id();
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM chat
    WHERE id = p_chat_id AND (user_a_id = v_login_id OR user_b_id = v_login_id)
  ) THEN
    RAISE EXCEPTION 'CHAT_PARTICIPANT_REQUIRED';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM message WHERE id = p_message_id AND chat_id = p_chat_id) THEN
    RAISE EXCEPTION 'MESSAGE_NOT_FOUND';
  END IF;
  IF NOT consume_rate_limit('read_receipt', v_login_id || ':' || p_chat_id, 120, 60) THEN
    RAISE EXCEPTION 'RATE_LIMITED';
  END IF;

  RETURN QUERY
  INSERT INTO chat_read_state (chat_id, user_id, last_read_message_id)
  VALUES (p_chat_id, v_login_id, p_message_id)
  ON CONFLICT (chat_id, user_id)
  DO UPDATE SET
    last_read_message_id = GREATEST(chat_read_state.last_read_message_id, EXCLUDED.last_read_message_id),
    read_at = now()
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.reset_chat(p_chat_id bigint)
RETURNS SETOF chat
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_login_id varchar(64) := current_login_id();
  v_now timestamptz := now();
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM chat
    WHERE id = p_chat_id AND status = 'active' AND (user_a_id = v_login_id OR user_b_id = v_login_id)
  ) THEN
    RAISE EXCEPTION 'CHAT_PARTICIPANT_REQUIRED';
  END IF;
  INSERT INTO chat_reset_log (chat_id, reset_by_user_id, reset_at)
  VALUES (p_chat_id, v_login_id, v_now);
  RETURN QUERY
  UPDATE chat SET last_reset_at = v_now WHERE id = p_chat_id RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.leave_chat(p_chat_id bigint)
RETURNS SETOF chat
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_login_id varchar(64) := current_login_id();
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM chat
    WHERE id = p_chat_id AND status = 'active' AND (user_a_id = v_login_id OR user_b_id = v_login_id)
  ) THEN
    RAISE EXCEPTION 'CHAT_PARTICIPANT_REQUIRED';
  END IF;
  RETURN QUERY
  UPDATE chat
  SET status = 'ended', ended_at = now(), ended_by_user_id = v_login_id
  WHERE id = p_chat_id
  RETURNING *;
END;
$$;

ALTER TABLE user_account ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat ENABLE ROW LEVEL SECURITY;
ALTER TABLE message ENABLE ROW LEVEL SECURITY;
ALTER TABLE media ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_reset_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_read_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_rate_limit ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_account_insert_own ON user_account
FOR INSERT TO authenticated WITH CHECK (auth_user_id = auth.uid());
CREATE POLICY user_account_select_own ON user_account
FOR SELECT TO authenticated USING (auth_user_id = auth.uid());
CREATE POLICY user_account_update_own ON user_account
FOR UPDATE TO authenticated USING (auth_user_id = auth.uid()) WITH CHECK (auth_user_id = auth.uid());

CREATE POLICY chat_select_participant ON chat
FOR SELECT TO authenticated USING (user_a_id = current_login_id() OR user_b_id = current_login_id());

CREATE POLICY message_select_participant ON message
FOR SELECT TO authenticated USING (
  EXISTS (
    SELECT 1 FROM chat
    WHERE chat.id = message.chat_id
      AND (chat.user_a_id = current_login_id() OR chat.user_b_id = current_login_id())
  )
);

CREATE POLICY media_select_participant ON media
FOR SELECT TO authenticated USING (
  EXISTS (
    SELECT 1 FROM message
    JOIN chat ON chat.id = message.chat_id
    WHERE message.id = media.message_id
      AND (chat.user_a_id = current_login_id() OR chat.user_b_id = current_login_id())
  )
);

CREATE POLICY reset_log_select_participant ON chat_reset_log
FOR SELECT TO authenticated USING (
  EXISTS (
    SELECT 1 FROM chat
    WHERE chat.id = chat_reset_log.chat_id
      AND (chat.user_a_id = current_login_id() OR chat.user_b_id = current_login_id())
  )
);

CREATE POLICY read_state_select_participant ON chat_read_state
FOR SELECT TO authenticated USING (
  EXISTS (
    SELECT 1 FROM chat
    WHERE chat.id = chat_read_state.chat_id
      AND (chat.user_a_id = current_login_id() OR chat.user_b_id = current_login_id())
  )
);

GRANT SELECT ON chat, message, media, chat_reset_log, chat_read_state TO authenticated;
GRANT INSERT ON user_account TO authenticated;
GRANT SELECT, UPDATE ON user_account TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_chat() TO authenticated;
GRANT EXECUTE ON FUNCTION public.join_chat(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.send_text_message(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_chat_read(bigint, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reset_chat(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.leave_chat(bigint) TO authenticated;

REVOKE ALL ON TABLE security_rate_limit FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.current_login_id() FROM anon, authenticated;
REVOKE ALL ON FUNCTION public.consume_rate_limit(text, text, integer, integer) FROM anon, authenticated;
